# Generated by Django 4.2.10 on 2024-06-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet',
            new_name='Question',
        ),
    ]
